// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs0ESHliRquJ64iOF5vDDg72WUCh1QIEQ',
    appId: '1:470946054114:web:17ac54ead73a5ff53b43bb',
    messagingSenderId: '470946054114',
    projectId: 'congressional-app-challe-e7216',
    authDomain: 'congressional-app-challe-e7216.firebaseapp.com',
    storageBucket: 'congressional-app-challe-e7216.appspot.com',
    measurementId: 'G-QDSLJDBBWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ZU2C2QebCfCLTeOfHTca9GQ0aSdVzTI',
    appId: '1:470946054114:android:f27e3ace9b2a94853b43bb',
    messagingSenderId: '470946054114',
    projectId: 'congressional-app-challe-e7216',
    storageBucket: 'congressional-app-challe-e7216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzyLRJa0w4CtlQ-cT76nInRT2xZLHefwI',
    appId: '1:470946054114:ios:d910f753a30753583b43bb',
    messagingSenderId: '470946054114',
    projectId: 'congressional-app-challe-e7216',
    storageBucket: 'congressional-app-challe-e7216.appspot.com',
    iosClientId: '470946054114-t765l43bqkmq7vubdk4l99dfcufi5sg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzyLRJa0w4CtlQ-cT76nInRT2xZLHefwI',
    appId: '1:470946054114:ios:943515125d0679d53b43bb',
    messagingSenderId: '470946054114',
    projectId: 'congressional-app-challe-e7216',
    storageBucket: 'congressional-app-challe-e7216.appspot.com',
    iosClientId: '470946054114-aof834qkcdni5o4c1crs91tflocqm9pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
